### ISSUE TITLE
[BUG]when I followed Contributing guildline ,found scripts/generate_release_notes.py:82: error: Module has no attribute "BooleanOptionalAction"  [attr-defined]

### ISSUE THREAD

**Issue by peter-ni-noob** [vacanza/python-holidays#1603] opened 2023-12-22 03:28 UTC
[env]linux unbuntu 18,python=3.8.raw conda envirionment.
I just follow the CONTRIBUTING.rst,and dont change anything,after "make setup","make pre-commit" is not passed because :
scripts/generate_release_notes.py:82: error: Module has no attribute "BooleanOptionalAction"  [attr-defined]
Found 1 error in 1 file (checked 339 source files)
rst ``code`` is two backticks............................................Passed
rstcheck.................................................................Failed
- hook id: rstcheck
- exit code: 1

WARNING:rstcheck_core.checker:An `AttributeError` error occured. This is most probably due to a code block directive (code/code-block/sourcecode) without a specified language. This may result in a false negative for source: 'docs/source/contributing.rst'. The reason can also be another directive. For more information see the FAQ (https://rstcheck-core.rtfd.io/en/latest/faq) or the corresponding github issue: https://github.com/rstcheck/rstcheck-core/issues/3.
WARNING:rstcheck_core.checker:An `AttributeError` error occured. This is most probably due to a code block directive (code/code-block/sourcecode) without a specified language. This may result in a false negative for source: 'docs/source/changelog.rst'. The reason can also be another directive. For more information see the FAQ (https://rstcheck-core.rtfd.io/en/latest/faq) or the corresponding github issue: https://github.com/rstcheck/rstcheck-core/issues/3.
WARNING:rstcheck_core.checker:An `AttributeError` error occured. This is most probably due to a code block directive (code/code-block/sourcecode) without a specified language. This may result in a false negative for source: 'docs/source/index.rst'. The reason can also be another directive. For more information see the FAQ (https://rstcheck-core.rtfd.io/en/latest/faq) or the corresponding github issue: https://github.com/rstcheck/rstcheck-core/issues/3.
docs/source/api.rst:4: (INFO/1) No directive entry for "automodule" in module "docutils.parsers.rst.languages.en".
docs/source/api.rst:4: (ERROR/3) Unknown directive type "automodule".
docs/source/api.rst:5: (INFO/1) No directive entry for "automodule" in module "docutils.parsers.rst.languages.en".
docs/source/api.rst:5: (ERROR/3) Unknown directive type "automodule".
docs/source/modules.rst:4: (INFO/1) No directive entry for "autosummary" in module "docutils.parsers.rst.languages.en".
docs/source/modules.rst:4: (ERROR/3) Unknown directive type "autosummary".
Error! Issues detected.

**Comment by peter-ni-noob** [comment] 2023-12-22 03:38
I found the cause of this problem is the version of python,it **need python 3.9+**,I think we need specify the version recommendation for this project.ref:https://stackoverflow.com/questions/15008758/parsing-boolean-values-with-argparse

**Comment by peter-ni-noob** [comment] 2023-12-22 03:47
or I can change the code to makes it compatible with python 3.8

**Comment by arkid15r** [comment] 2023-12-22 18:22
Hi @peter-ni-noob, it seems you're right as `BooleanOptionalAction` is not available for python3.8
The issue is with our internal script that supports our release process. I guess it'd be fine just suppress the error if possible.

I'll look into it. Thanks for bringing this up!

**Comment by arkid15r** [comment] 2024-01-06 20:52
Fixed in https://github.com/vacanza/python-holidays/pull/1627

**Closed by arkid15r** 2024-01-06 20:52 UTC
