### ISSUE TITLE
DeprecationWarning after release of 0.38

### ISSUE THREAD

**Issue by karrmagadgeteer2** [vacanza/python-holidays#1582] opened 2023-12-04 20:33 UTC
I have a project where holidays is a dependency. I run Python 3.10 on Linux and Windows. This error only shows on Linux. The error was first noticed in a Github action Linux workflow. Then tested also on Windows WSL. It breaks during the collection phase of my test suite. If I pin the holidays version to 0.37 the error goes away.

Apologies if this is a bit thin. I am a self taught in Python mostly.

![image](https://github.com/vacanza/python-holidays/assets/13209112/e5062022-746c-4cbc-9d00-3b948275815a)

**Comment by arkid15r** [comment] 2023-12-04 20:39
Hi Martin, thanks for reporting this.

I guess the issue is related to one of the [recent changes](https://github.com/vacanza/python-holidays/pull/1564/files#diff-3835a4c66a509f1de886fe22c21ea9c22d7e83d49203fdb4dfc448ec56527549R23). I'll try to look into this today or tomorrow. It's interesting our CI/CD didn't catch it.

**Comment by karrmagadgeteer2** [comment] 2023-12-04 20:55
Before you do any work... I have the below section in my pyproject.toml config file. When I remove it the test suite runs as intended. I suspect the fail is because this section ignores your `noqa W605`.

```
[tool.pytest.ini_options]
filterwarnings = [
    "error",
    'ignore::DeprecationWarning:dateutil.*:',
    'ignore::DeprecationWarning:openpyxl.*:',
    "ignore::DeprecationWarning:pandas_datareader.*:"
]
```

**Comment by arkid15r** [comment] 2023-12-04 21:12
It's good to know, thanks for adding more context!

**Comment by arkid15r** [comment] 2024-01-01 19:26
I believe this was fixed in https://github.com/vacanza/python-holidays/pull/1619

**Closed by arkid15r** 2024-01-01 19:26 UTC
